apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-service
  labels:
    app: student-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-service
  template:
    metadata:
      labels:
        app: student-service
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: student-service
        image: oluchioraekwe/studentservice:latest
        imagePullPolicy: "Always"
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
          requests:
            cpu: "200m"
        ports:
        - containerPort: 5050
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: database-url
        - name: BASEURL_AUTH
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: authservice-url
        - name: PORT
          value: "5050"
        - name : ME_CONFIG_MONGODB_AUTH_DATABASE
          value: students
        - name : PORT_AUTH
          value: "4000"
        - name: NODE_ENV
          value: "minikube"

---
apiVersion: v1
kind: Service
metadata:
  name: student-micro-service
spec:
  selector:
    app: student-service
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
      nodePort: 30000
